import Navbar from './components/Navbar';
import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className='h-screen flex flex-col'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
