import './globals.css';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import Link from 'next/link';
import Navbar from './components/Navbar';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${rubik.className} h-screen flex flex-col`}>
        <Navbar />
        {children}
        <footer className='bg-green-800 text-white text-center p-8'>
          About Page Footer
        </footer>
      </body>
    </html>
  );
}
